-- test tables

CREATE TABLE IF NOT EXISTS PERSON (
	PERSON_KEY VARCHAR(255),
	NAME VARCHAR(255),
	ATTRIBUTES JSONB,                     /* VARIANT */
	CREATED TIMESTAMP NOT NULL,           /* TIMESTAMP_NTZ(9) */
	STATUS NUMERIC(38,0),                 /* NUMBER(38,0) */
	CONSTRAINT person_pk PRIMARY KEY (PERSON_KEY)
);

CREATE TABLE IF NOT EXISTS WORKPLACE (
	WORKPLACE_KEY VARCHAR(255),
	ADDRESS VARCHAR(255) NOT NULL,
	PERSON_FK VARCHAR(255),
	ID BIGSERIAL NOT NULL,                       /* NUMBER(38,0) autoincrement */
CONSTRAINT workplace_pk PRIMARY KEY (WORKPLACE_KEY, ADDRESS),
CONSTRAINT person_fk FOREIGN KEY (PERSON_FK)
    REFERENCES PERSON(PERSON_KEY) ON UPDATE RESTRICT ON DELETE RESTRICT
);

      





